name: Deploy Tracker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar deploy en servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            /home/admin/scripts/tracker/tracker-update.sh